version: 2
updates:
  # - package-ecosystem: "gomod"
  #   directory: "/tests/e2e"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "10:00"
  #   open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5

  # - package-ecosystem: "terraform"
  #   directory: "/k8s-the-easy-way"
  #   schedule:
  #     interval: "weekly"
  #     day: "monday"
  #     time: "10:00"
  #   open-pull-requests-limit: 5
