---
global:
  # Default image used by all components
  image:
    # -- If defined, a repository applied to all Argo CD deployments
    repository: quay.io/argoproj/argocd
    # tag: "v3.3.10@sha256:05d68bf224df7cd39713012c19226a33c374f2f3bd65df7b9088349e4ac3e6a2"
configs:
  params:
    reposerver.git.request.timeout: "300s"
  cm:
    # -- Timeout to discover if a new manifests version got published to the repository
    timeout.reconciliation: 305s
dex:
  enabled: false
controller:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
server:
  config:
    url: http://argocd.127.0.0.1.nip.io
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  extraArgs:
    - --insecure
    - --disable-auth
  ingress:
    enabled: true
    hostname: "argocd.127.0.0.1.nip.io"
redis:
  metrics:
    enabled: true
applicationSet:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
