apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: security-falco
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 1.19.1
    helm:
      values: |
        falco:
          grpc:
            enabled: true
          grpcOutput:
            enabled: true
        falcosidekick:
          enabled: true
          ingress:
            enabled: true
            hosts:
              - host: falcosidekick.157.245.20.216.nip.io
                paths:
                  - path: /
          webui:
            enabled: true
            darkmode: true
            ingress:
              enabled: true
              hosts:
              - host: falcosidekick-ui.157.245.20.216.nip.io
                paths:
                - path: /ui
                  # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.)
                  # pathType: Prefix
                - path: /events
                  # pathType: Prefix
                - path: /healthz
                  # pathType: Prefix
                - path: /ws
                  # pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: falco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
