apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: security-trivy
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.31.0
    helm:
      values: |
        operator:
          vulnerabilityScannerScanOnlyCurrentRevisions: true
          configAuditScannerScanOnlyCurrentRevisions: true
        trivy:
          ignoreUnfixed: true
          imageRef: ghcr.io/aquasecurity/trivy:0.30.4
        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustercompliancereports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustercompliancedetailreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: ciskubebenchreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clusterconfigauditreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: clustervulnerabilityreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: kubehunterreports.aquasecurity.github.io
      jsonPointers:
        - /spec/names/categories
