apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starboard-exporter
  namespace: argocd
spec:
  project: security-trivy
  source:
    chart: starboard-exporter
    repoURL: https://giantswarm.github.io/giantswarm-catalog
    targetRevision: 0.7.4
    helm:
      values: |
        monitoring.grafanaDashboard.namespace: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
